[default]
port = 3000
dist_dir = "dist/"

[release.database]
url = "postgres://postgres:postgres@localhost:5432/jobs_feed"

[debug.database]
url = "postgres://postgres:postgres@localhost:5432/jobs_feed_debug"
