//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "extraction")]
pub struct Model {
	#[sea_orm(primary_key)]
	#[serde(skip_deserializing)]
	pub id: i32,
	pub created_at: Option<DateTimeWithTimeZone>,
	pub model: Option<String>,
	pub prompt_tokens: Option<i32>,
	pub completion_tokens: Option<i32>,
	#[sea_orm(column_type = "Float", nullable)]
	pub cost: Option<f32>,
	pub source_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::source::Entity",
		from = "Column::SourceId",
		to = "super::source::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Source,
}

impl Related<super::source::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Source.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
