//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::embedding::Entity as Embedding;
pub use super::filter::Entity as Filter;
pub use super::posting::Entity as Posting;
pub use super::settings::Entity as Settings;
pub use super::source::Entity as Source;
pub use super::suggestion::Entity as Suggestion;
